name: "🐞 Bug Report"
description: "Something is wrong with PATCH-MAP"
title: "Bug: "
labels: ['🐞 Bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: current_behavior
    # 현재 동작 (필수)
    attributes:
      label: "Current Behavior"
      placeholder: "Leave a comment"
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    # 예상 동작 (필수)
    attributes:
      label: "Expected Behavior"
      placeholder: "Leave a comment"
    validations:
      required: true

  - type: textarea
    id: steps
    # 재현 단계 (필수)
    attributes:
      label: "Steps to Reproduce"
      placeholder: "If possible, provide a link to a reproducible example or include the relevant code."
    validations:
      required: true

  - type: input
    id: environment
    # 환경 정보 (필수)
    attributes:
      label: "Environment"
      placeholder: "Output of `npx envinfo --system --npmPackages @conalog/patch-map --binaries --browsers`"
    validations:
      required: true

  - type: textarea
    id: additional_context
    # 추가 정보 (선택)
    attributes:
      label: "Additional Context"
      placeholder: "Leave a comment"