name: "🐞 Bug Report"
description: "Something is wrong with PATCH-MAP"
title: "Bug: "
labels: ['🐞 Bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "Bug description"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Reproduction"
      description: "How do you trigger this bug? Please walk us through it step by step."
      placeholder: "Reproduction"
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Output of `npx envinfo --system --npmPackages @conalog/patch-map --binaries --browsers`"
      placeholder: "System, Binaries, Browsers, npmPackages"
    validations:
      required: true