name: "💡 Feature Request"
description: "Suggest a new feature or improvement"
title: "Feature: "
labels: ['💡 Feature Request']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request this feature!

  - type: textarea
    id: problem
    # 문제 설명 (필수)
    attributes:
      label: "Describe the problem"
      description: "Briefly describe the problem this feature would solve. More details would be helpful."
      placeholder: "Leave a comment"
    validations:
      required: true

  - type: textarea
    id: solution
    # 솔루션 설명 (필수)
    attributes:
      label: "Describe the proposed solution"
      description: "Clearly and concisely describe the desired outcome."
      placeholder: "Leave a comment"
    validations:
      required: true