export const FONT_WEIGHT = {
  100: 'Thin',
  200: 'ExtraLight',
  300: 'Light',
  400: 'Regular',
  500: 'Medium',
  600: 'SemiBold',
  700: 'Bold',
  800: 'Extra-Bold',
  900: 'Black',
  thin: 'Thin',
  extralight: 'ExtraLight',
  light: 'Light',
  regular: 'Regular',
  medium: 'Medium',
  semibold: 'SemiBold',
  bold: 'Bold',
  extrabold: 'Extra-Bold',
  black: 'Black',
};
