import { describe, expect, it } from 'vitest';

import {
  PATCH_MAP_EXECUTABLE_CASE_IDS,
  materializePatchMapExecutableCase,
} from '../../lab/patch-map/contract/executable-cases';
import { resolvePatchMapExecutableRuntime } from '../../lab/patch-map/contract/executable-runtime';

describe('PatchMap executable Lab product bridge', () => {
  it('selects one collision-free handler/fold runtime descriptor for every executable case', () => {
    const runtimeByCase = Object.fromEntries(
      PATCH_MAP_EXECUTABLE_CASE_IDS.map((caseId) => [
        caseId,
        resolvePatchMapExecutableRuntime(caseId).key,
      ]),
    );

    expect(runtimeByCase).toEqual({
      'EVT-001': 'pointer-selection',
      'EVT-002': 'pointer-selection',
      'EVT-003': 'pointer-selection',
      'EVT-004': 'pointer-selection',
      'EVT-005': 'pointer-selection',
      'EVT-006': 'pointer-selection',
      'EVT-007': 'pointer-selection',
      'EVT-008': 'pointer-selection',
      'EVT-009': 'pointer-selection',
      'HIS-001': 'history',
      'HIS-002': 'history',
      'HIS-003': 'history',
      'HIS-004': 'history',
      'HIS-005': 'history',
      'HIS-006': 'history',
      'ERR-001': 'update-transactions',
      'ERR-002': 'replacement-recovery',
      'ERR-003': 'asset-ingestion',
      'ERR-004': 'lifecycle-interruption',
      'ERR-005': 'replacement-recovery',
      'ERR-006': 'lifecycle-interruption',
      'DET-001': 'determinism-lifecycle',
      'DET-002': 'determinism-lifecycle',
      'DET-003': 'determinism-lifecycle',
      'DET-004': 'export-extraction',
      'PRF-001': 'performance',
      'PRF-002': 'performance',
      'PRF-003': 'performance',
      'PRF-004': 'performance',
      'PRF-005': 'performance',
      'PRF-006': 'performance',
      'PRF-007': 'lifecycle-interruption',
      'PRF-008': 'export-extraction',
      'PRF-009': 'performance',
      'LIF-001': 'foundation',
      'LIF-002': 'foundation',
      'LIF-003': 'replacement-recovery',
      'LIF-004': 'lifecycle-resize',
      'LIF-005': 'lifecycle-destroy',
      'LIF-006': 'determinism-lifecycle',
      'ACC-001': 'accessibility',
      'ACC-002': 'accessibility',
      'ACC-003': 'accessibility',
      'OPS-001': 'security-operations',
      'OPS-002': 'security-operations',
      'MIG-001': 'migration',
      'MIG-002': 'migration',
      'MIG-003': 'migration',
      'DAT-001': 'foundation',
      'DAT-002': 'foundation',
      'DAT-003': 'data-foundation',
      'DAT-004': 'data-foundation',
      'DAT-005': 'data-foundation',
      'DAT-006': 'data-closure',
      'DAT-007': 'data-closure',
      'DAT-008': 'data-closure',
      'PIX-001': 'pixijs-integration',
      'PIX-002': 'pixijs-integration',
      'PIX-003': 'pixijs-integration',
      'PIX-004': 'export-extraction',
      'PIX-005': 'pixijs-integration',
      'PKG-001': 'package-integration',
      'PKG-002': 'package-integration',
      'PKG-003': 'package-integration',
      'PKG-004': 'package-integration',
      'PKG-005': 'package-integration',
      'AST-001': 'assets',
      'AST-002': 'asset-ingestion',
      'AST-003': 'asset-ingestion',
      'SEC-001': 'asset-ingestion',
      'SEC-002': 'security-operations',
      'SEC-003': 'security-operations',
      'SEC-004': 'security-operations',
      'UPD-001': 'update-transactions',
      'UPD-002': 'update-transactions',
      'UPD-003': 'update-transactions',
      'UPD-004': 'update-transactions',
      'UPD-005': 'presentation-dynamics',
      'UPD-006': 'update-transactions',
      'UPD-007': 'update-transactions',
      'UPD-008': 'update-transactions',
      'UPD-009': 'update-transactions',
      'UPD-010': 'update-transactions',
      'UPD-011': 'update-transactions',
      'UPD-012': 'update-transactions',
      'UPD-013': 'update-transactions',
      'UPD-014': 'update-transactions',
      'VIE-001': 'viewport',
      'QRY-001': 'query-selection',
      'QRY-002': 'query-selection',
      'SEL-001': 'query-selection',
      'SEL-002': 'query-selection',
      'SEL-003': 'query-selection',
      'SEL-004': 'query-selection',
      'SEL-005': 'pointer-selection',
      'SEL-006': 'pointer-selection',
      'SEL-007': 'pointer-selection',
      'SEL-008': 'pointer-selection',
      'SEL-009': 'pointer-selection',
      'TRN-001': 'pointer-selection',
      'TRN-002': 'pointer-selection',
      'TRN-003': 'pointer-selection',
      'TRN-004': 'pointer-selection',
      'TRN-005': 'pointer-selection',
      'TRN-006': 'pointer-selection',
      'TRN-007': 'pointer-selection',
      'TRN-008': 'pointer-selection',
      'TRN-009': 'pointer-selection',
      'TRN-010': 'pointer-selection',
      'VIE-002': 'viewport',
      'VIE-003': 'viewport',
      'VIE-004': 'viewport',
      'VIE-005': 'viewport',
      'VIE-006': 'viewport',
      'VIE-007': 'viewport',
      'VIE-008': 'viewport',
      'ANI-001': 'presentation-dynamics',
      'ANI-002': 'presentation-dynamics',
      'ANI-003': 'determinism-lifecycle',
      'CSM-001': 'foundation',
      'CSM-002': 'replacement-recovery',
      'CSM-003': 'foundation',
      'CSM-004': 'replacement-recovery',
      'CSM-005': 'update-transactions',
      'CSM-006': 'update-transactions',
      'CSM-007': 'update-transactions',
      'CSM-008': 'update-transactions',
      'CSM-009': 'viewport',
      'CSM-010': 'viewport',
      'CSM-011': 'pointer-selection',
      'CSM-012': 'pointer-selection',
      'CSM-013': 'interaction-editor',
      'CSM-014': 'update-transactions',
      'CSM-015': 'pointer-selection',
      'CSM-016': 'pointer-selection',
      'CSM-017': 'lifecycle-interruption',
      'CSM-018': 'interaction-editor',
      'CSM-019': 'authoring',
      'CSM-020': 'pointer-selection',
      'CSM-021': 'pointer-selection',
      'CSM-022': 'interaction-editor',
      'CSM-023': 'interaction-editor',
      'CSM-024': 'interaction-editor',
      'CSM-025': 'editor-workflow',
      'CSM-026': 'editor-workflow',
      'CSM-027': 'editor-workflow',
      'CSM-028': 'authoring',
      'CSM-029': 'authoring',
      'CSM-030': 'authoring',
      'CSM-031': 'authoring',
      'CSM-032': 'asset-ingestion',
      'CSM-033': 'editor-workflow',
      'CSM-034': 'editor-workflow',
      'CSM-035': 'export-extraction',
      'CSM-036': 'lifecycle-interruption',
      'CSM-037': 'replacement-recovery',
      'CSM-038': 'export-extraction',
      'LAY-001': 'render-foundation',
      'LAY-002': 'layout-order',
      'LAY-003': 'layout-order',
      'LAY-004': 'render-orientation',
      'LAY-005': 'render-bounds',
      'REN-001': 'render-foundation',
      'REN-004': 'render-foundation',
      'REN-005': 'render-images',
      'REN-006': 'render-text',
      'REN-008': 'render-component-assets',
      'REN-009': 'presentation-dynamics',
      'REN-010': 'render-component-assets',
      'REN-011': 'render-text',
      'REN-003': 'render-foundation',
      'REN-002': 'render-foundation',
      'REN-007': 'render-relations',
    });

    for (const caseId of PATCH_MAP_EXECUTABLE_CASE_IDS) {
      const plan = materializePatchMapExecutableCase(caseId, '100', 319);
      const handlerIds = resolvePatchMapExecutableRuntime(caseId)
        .handlerEntries(plan)
        .map(([handlerId]) => handlerId);
      const expectedHandlerIds = [...new Set(
        plan.actionTrace.map((action) => `contract/${action.type}`),
      )];
      expect(handlerIds).toHaveLength(new Set(handlerIds).size);
      expect([...handlerIds].sort()).toEqual([...expectedHandlerIds].sort());
    }
  });
});
